//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomHonda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.HINHANHs = new HashSet<HINHANH>();
            this.PHIEUBAOHANHs = new HashSet<PHIEUBAOHANH>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MauSac { get; set; }
        public string MaKT { get; set; }
        public string MaLoai { get; set; }
        public string MaGG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual GIAMGIA GIAMGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH> HINHANHs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUBAOHANH> PHIEUBAOHANHs { get; set; }
        public virtual THONGSOKYTHUAT THONGSOKYTHUAT { get; set; }
    }
}
