//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowroomHonda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGSOKYTHUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGSOKYTHUAT()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public string MaKT { get; set; }
        public string KhoiLuongKho { get; set; }
        public string DaiRongCao { get; set; }
        public string KhoangCachTruc { get; set; }
        public string DoCaoYen { get; set; }
        public string KhoangSangGam { get; set; }
        public string DungTichBinhXang { get; set; }
        public string KichCoLopTruoc { get; set; }
        public string KichCoLopSau { get; set; }
        public string PhuocTruoc { get; set; }
        public string PhuocSau { get; set; }
        public string LoaiDongCo { get; set; }
        public string CongXuatToiDa { get; set; }
        public string DungTichNhot { get; set; }
        public string MucTieuThu { get; set; }
        public string LoaiTruyenDong { get; set; }
        public string HeThongKhoiDong { get; set; }
        public string MomenCucDai { get; set; }
        public string DungTichXiLanh { get; set; }
        public string DuongKinhHanhTrinhPiston { get; set; }
        public string TiSoNen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
